In [17]:
#1. 建立一個長度為 15 的隨機向量，每個數值介在 0~2 hint: random.rand
import numpy as np
ran=np.random.rand(15)*2
print(ran)
# ran=np.random.uniform(0,2,15)
# print(ran)



[0.71291432 0.56962044 1.30362028 1.12104519 1.76770443 0.44096761
 1.38605719 1.38274828 1.52380078 1.53498381 1.6218932  0.28882384
 1.79891527 0.55539577 1.76262101]
CPU times: total: 0 ns
Wall time: 7.68 ms


In [20]:
#2. 建立一个 6 x 6 的矩陣，其中每個的數值介在 0~5 hint: reshape
arr66=np.random.uniform(0, 5, 36).reshape(6, 6)
print(arr66)

[[1.92276181 2.02065348 2.90706162 3.87430226 4.77856001 0.47198777]
 [0.35582582 2.02823229 2.71208773 3.35290007 2.52862007 1.25529209]
 [1.73896012 1.208582   1.79989492 3.54806245 3.00836424 2.31158403]
 [4.29561154 1.24104617 3.34226105 0.6882724  4.81391624 1.04647228]
 [0.70460356 3.44983533 4.35972853 2.14724069 4.15975269 1.55901144]
 [2.17816756 1.18114587 1.76215357 3.24663221 0.61288342 4.16488014]]


In [32]:
#3. 建立一個 3x3x3 的隨機矩陣，分別計算所有的、按照 axis=0、按照 axis=2 的 mean
arr333=np.random.rand(27).reshape(3,3,3)
print("arr333:",arr333)
print("---------")
print("all average:",arr333.mean())
print("---------")
print("axis=0:",arr333.mean(axis=0))
print("---------")
print("axis=2:",arr333.mean(axis=2))

arr333: [[[0.05383057 0.52644241 0.24529059]
  [0.51388528 0.27133579 0.59977987]
  [0.80035619 0.48587969 0.45002657]]

 [[0.86092562 0.25684913 0.60618674]
  [0.36542158 0.30730961 0.25490181]
  [0.19789971 0.99486046 0.19891635]]

 [[0.57781369 0.62004454 0.54721464]
  [0.63383736 0.00980788 0.09466831]
  [0.26390258 0.48614024 0.67709772]]]
---------
all average: 0.4407638858199757
---------
axis=0: [[0.49752329 0.46777869 0.46623066]
 [0.50438141 0.19615109 0.31645   ]
 [0.42071949 0.6556268  0.44201355]]
---------
axis=2: [[0.27518786 0.46166698 0.57875415]
 [0.57465383 0.309211   0.46389217]
 [0.58169095 0.24610452 0.47571351]]


In [38]:
#4. 了解 reshape、dot 或任意 numpy function 的用法，並舉出兩個實際操作的例子
#example 1: dot()
a1=np.random.randint(0,10,(2,2))
a2=np.random.randint(0,10,(2,2))
print("a1:",a1)
print("a2:",a2)
matrix_multiplication=np.dot(a1,a2)
print("matrix multiplication:",matrix_multiplication)

#example 2: concatenate()
print("concatenate two array(axis=0):",np.concatenate([a1,a2]))
print("concatenate two array(axis=1):",np.concatenate([a1,a2],axis=1))


a1: [[9 9]
 [3 8]]
a2: [[4 8]
 [8 2]]
matrix multiplication: [[108  90]
 [ 76  40]]
concatenate two array: [[9 9]
 [3 8]
 [4 8]
 [8 2]]
concatenate two array(axis=0): [[9 9 4 8]
 [3 8 8 2]]
