In [9]:
#1. 建立一個 6x6 的矩陣，讓 1,2,3,4,5 落在對角線上，並取出部分 matrix hint:
import numpy as np
a=np.zeros(36).reshape(6, 6)
for i in range(1,7):
    a[i-1][i-1]=i
print("matrix:\n",a)
print("partial:\n",a[2:5, 2:5])

matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]
partial:
 [[3. 0. 0.]
 [0. 4. 0.]
 [0. 0. 5.]]


In [15]:
#2. 建立從 0 ~ pi * 2 的隨機 array，裡面包含 21 個元素，並對該陣列取 cos 或 sin
a=np.random.rand(21)*np.pi*2
print("array(0~pi*2):\n",a)
print("cos(a):\n",np.cos(a))

array(0~pi*2):
 [6.1624623  3.41805289 4.56558686 2.46515666 2.95399146 4.60656495
 3.32200688 2.48349704 1.85688864 3.04310731 5.33794017 0.46214023
 2.29090511 0.35555106 0.9548836  5.28351397 4.87211251 5.69801466
 3.95485184 3.88485111 5.08794161]
cos(a):
 [ 0.99272182 -0.96202765 -0.14627541 -0.7798088  -0.98245445 -0.10562662
 -0.98376945 -0.79115841 -0.28220554 -0.99515424  0.58554417  0.8951003
 -0.65946645  0.9374548   0.57770378  0.54057884  0.15904526  0.83361784
 -0.68713419 -0.73626751  0.3667867 ]


In [20]:
#3. 請找一個 numpy 有關 數值運算、線性代數的函式，並附上至少兩個範例 code
a=np.linspace(10, 20, 5, endpoint=False)   #10~20(不包含)等差的5個數
b=np.linspace(1, 30, 7, endpoint=True)   #1~30(包含)等差的7個數
c=np.logspace(10, 1000, 5, endpoint=True)   #10~1000(包含)等比(以10為底)的5個數
print("a:\n",a)
print("b:\n",b)
print("c:\n",c)


a:
 [10. 12. 14. 16. 18.]
b:
 [ 1.          5.83333333 10.66666667 15.5        20.33333333 25.16666667
 30.        ]
c:
 [1.00000000e+010 3.16227766e+257             inf             inf
             inf]
